# Generated by Django 5.2.11 on 2026-03-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_monitoringreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
