# Generated by Django 5.2.11 on 2026-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_progress_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringreport',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='female',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='male',
            field=models.IntegerField(default=0),
        ),
    ]
