# Generated by Django 5.2.11 on 2026-03-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_monitoringreport_children_monitoringreport_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringreport',
            name='beneficiaries_reached',
            field=models.IntegerField(default=0),
        ),
    ]
