# Generated by Django 5.2.11 on 2026-03-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_monitoringreport_beneficiaries_reached'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringreport',
            name='critical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='warning',
            field=models.IntegerField(default=0),
        ),
    ]
