# Generated by Django 5.2.11 on 2026-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_monitoringreport_critical_monitoringreport_good_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringreport',
            name='critical',
        ),
        migrations.RemoveField(
            model_name='monitoringreport',
            name='good',
        ),
        migrations.RemoveField(
            model_name='monitoringreport',
            name='warning',
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
