# Generated by Django 5.2.11 on 2026-05-05 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('FOOD', 'Food Security'), ('HEALTH', 'Health'), ('EDU', 'Education'), ('SHELTER', 'Shelter')], max_length=20)),
                ('donor', models.CharField(max_length=200)),
                ('proposed_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('target_beneficiaries', models.IntegerField()),
                ('summary', models.TextField(blank=True, help_text='ملخص للبروبوزال (الأهداف، الأنشطة الرئيسية، المؤشرات...)', null=True)),
                ('proposal_file', models.FileField(blank=True, help_text='ارفع ملف البروبوزال (PDF, Word, ...)', null=True, upload_to='proposals/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to donor'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='core.project')),
            ],
        ),
    ]
